spring:
  application:
    name: flightfury-service-discovery

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true
#    status-page-url: ${server.servletPah}/info
#    secure-health-check-url: ${server.servletPath}/health

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF

