services:

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'

  mysql:
    image: mysql:oraclelinux9
    environment:
      MYSQL_USER: abderrahim
      MYSQL_PASSWORD: abderrahim
    ports:
      - '3306:3306'

  aircrafts:
    build:
      context: flightfury-aircrafts
      dockerfile: Dockerfile
    container_name: aircrafts-service
    depends_on:
      - mysql

  manufacturers:
    image: eclipse-temurin:21-alpine
    container_name: manufacturers-service
    build:
      context: flightfury-manufacturers
      dockerfile: Dockerfile
    depends_on:
      - mongo

  eureka-server:
    image: eclipse-temurin:21-alpine
    container_name: discovery-service
    ports:
      - '8761:8761'

  gateway:
    image: eclipse-temurin:21-alpine
    container_name: gateway-service
    ports:
      - '8082:8082'