server:
  port: ${AIRCRAFTS_SERVICE_PORT:8080}

logging:
  level:
    web: debug

spring:
  application:
    name: flightfury-aircrafts
  data:
    rest:
      base-path: "/"
      max-page-size: 20
  datasource:
    url: ${AIRCRAFTS_DB_URL:jdbc:mysql://localhost:3306/testdb}
    username: ${AIRCRAFTS_DB_USERNAME:abderrahim}
    password: ${AIRCRAFTS_DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never