server:
  port: 8081

logging:
  level:
    web: debug

debug: true

spring:
  application:
    name: flightfury-manufacturers
  datasource:
    url: mongodb://localhost:27017
  data:
    mongodb:
      database: manufacturers
      port: 27017