server:
  port: 8081

logging:
  level:
    web: debug

debug: true

spring:
  application:
    name: flightfury-manufacturers
  datasource:
    url: ${MANUFACTURERS_DB_URL:mongodb://localhost:27017}
  data:
    mongodb:
      database: ${MANUFACTURERS_DB_NAME:manufacturers}
      port: ${MANUFACTURERS_DB_PORT:27017}